package com.example.smallbusinessmanagementsystem.utilities;

public enum ControllerOperation {
    CREATE,
    UPDATE,
    REVIEW,
    FIND_FOR_PRODUKTAS,
    FIND_FOR_KOMUNIKACIJA,
    FIND_FOR_SANDELIS,
    FIND_FOR_TVARKARASTIS,
    FIND_FOR_FINANSAS,
    FIND_FOR_PARDAVIMAS,
    FIND_FOR_STATISTIKA_PRODUKTAI,
    FIND_FOR_STATISTIKA_KLIENTAI,
    FIND_FOR_STATISTIKA_ZYMES,
    FIND_FOR_STATISTIKA_FINANSAI,
    INCREASE,
    DECREASE;
}
